// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketVendor.Data;

namespace TicketVendor.Migrations
{
    [DbContext(typeof(TicketVendorContext))]
    [Migration("20190321131557_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketVendor.TicketVendor", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Act")
                        .IsRequired();

                    b.Property<double>("Cost");

                    b.Property<DateTime>("Date");

                    b.Property<string>("EventDescription")
                        .IsRequired();

                    b.Property<string>("EventTitle")
                        .IsRequired();

                    b.Property<string>("TicketType")
                        .IsRequired();

                    b.Property<int>("TicketsAvailable");

                    b.Property<string>("Venue")
                        .IsRequired();

                    b.HasKey("TicketID");

                    b.ToTable("TicketVendors");
                });
#pragma warning restore 612, 618
        }
    }
}
